results_dir: /results/
dataset:
  contiguous_id: True
  label_map: /specs/merged_labelmap.json
  train:
    type: 'coco_panoptic'
    name: "coco_2020_train_panoptic"
    panoptic_json: "/data/raw-data/annotations/training_shape_training2020_f_isthing.json" # v
    img_dir: "/data/raw-data/training" # v
    panoptic_dir: "/data/raw-data/semantic_training" # v
    batch_size: 16
    num_workers: 2
  val:
    type: 'coco_panoptic'
    name: "coco_2020_val_panoptic"
    panoptic_json: "/data/raw-data/annotations/training_shape_training2020_f_isthing.json" # v
    img_dir: "/data/raw-data/training" # v
    panoptic_dir: "/data/raw-data/semantic_training" # v
    batch_size: 1
    num_workers: 2
  test:
    img_dir: /data/raw-data/validation # v
    batch_size: 1
  augmentation:
    train_min_size: [640]
    train_max_size: 2048
    train_crop_size: [640, 640]
    test_min_size: 640
    test_max_size: 2048
train:
  precision: 'fp16'
  num_gpus: 1
  checkpoint_interval: 1
  validation_interval: 1
  # set the training epochs here
  num_epochs: 40
  # num_epochs: 1
  optim:
    lr_scheduler: "MultiStep"
    milestones: [34, 38]
    type: "AdamW"
    lr: 0.0001
    weight_decay: 0.05
model:
  object_mask_threshold: 0.
  overlap_threshold: 0.8
  mode: "semantic"
  backbone:
    # set the pretrained weights here!!!
    # pretrained_weights: "/workspace/tao-experiments/mask2former/swin_large_patch4_window12_384_22k.pth"
    pretrained_weights: "/workspace/tao-experiments/mask2former/swin_tiny_patch4_window7_224_22k.pth"
    # pretrained_weights: "/workspace/tao-experiments/mask2former/self_train_model_final.pth"
    type: "swin"
    swin:
      type: "tiny"  # change from tiny to large
      window_size: 7
      ape: False
      pretrain_img_size: 224
  mask_former:
    num_object_queries: 100
  sem_seg_head:
    norm: "GN"
    num_classes: 222 # 133 if contiguous_id
export:
  input_channel: 3
  input_width: 640
  input_height: 640
  opset_version: 17
  batch_size: -1  # dynamic batch size
  on_cpu: False
gen_trt_engine:
  gpu_id: 0
  input_channel: 3
  input_width: 640
  input_height: 640
  tensorrt:
    data_type: fp16
    workspace_size: 4096
    min_batch_size: 1
    opt_batch_size: 1
    max_batch_size: 1
